version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env.docker.local
    volumes:
      - postgres:/data/postgres
    ports:
      - "5430:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env.docker.local
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: